#!/bin/sh

# Use neovim for vim if present.
export EDITOR=nvim
command -v nvim >/dev/null && alias vimdiff="nvim -d"
# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="\cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	mail="neomutt" \
	ls="exa"\
	la="exa -a" \
	al="exa -a" \
	ll="exa -l" \
	l="exa -la" \
	tree="exa -T"\
	grep="grep --color=auto" \
	psg="ps -A | grep -i" \
	psf="ps -A | fzf" \
	gacp="git add . ; git commit ; git push" \
	g="git" \
	gis="git status" \
	gac="git add . ; git commit"\
	gr="cd \`git rev-parse --show-toplevel\`"


# Colorize commands when possible.
alias \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	sl="ls" \
	trem="transmission-remote" \
	YT="youtube-viewer -C -7" \
	sdn="sudo shutdown -h now" \
	doas="sudo"\
	du="du -h" \
	e="exit" \
	v="$EDITOR" \
	vim="$EDITOR"\
	p="sudo pacman" \
	cu="cd .." \
	alias fd="fd --no-ignore"\
	:q="exit" \
	:w="clear"\
	:wq="exit"
	# xi="sudo xbps-install" \
	# xr="sudo xbps-remove -R" \
	# xq="xbps-query"\

# Some other stuff
alias \
	ca="cargo" \
	cab="cargo build" \
	cabr="cargo build --release" \
	car="cargo run" \
	carr="cargo run --release" \
	cart="cargo test" \
	cac="cargo check" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	dvtm="dvtm -m ^n" \
	t="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"\
	ta="t a"\
	opus2mp3="mkdir encoded; for f in *.opus; do ffmpeg -i \"\$f\" "encoded/\$f.mp3"; done"\
	c="clear"\
	tl="tmux ls"\
  serve="live-server"
function controlt () {
    curdir=`pwd`
    cd `git rev-parse --show-toplevel`
    file=$(git ls-files|fzf)
    case $? in
      1) nvim $file;;
      130) ;;
    esac
    cd $curdir
}
